"""

Revision ID: 52035c36b1e5
Revises: 78bf377b5207
Create Date: 2024-01-13 08:15:08.975001

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52035c36b1e5"
down_revision: Union[str, None] = "78bf377b5207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vote", sa.Column("like", sa.Boolean(), nullable=False))
    op.drop_column("vote", "choice")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vote",
        sa.Column(
            "choice",
            postgresql.ENUM("in_favor", "against", name="variant"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("vote", "like")
    # ### end Alembic commands ###
