# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x63ommunication.proto\x12\rcommunication"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t"\x1f\n\x0c\x42\x61lanceReply\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\t"\x0e\n\x0c\x42lockRequest"Z\n\nBlockReply\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x1a\n\x12\x63ount_transactions\x18\x02 \x01(\x05\x12\x12\n\ndifficulty\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01(\t"\'\n\x14VerifyAddressRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t")\n\x12VerifyAddressReply\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\x32\xfb\x01\n\x0c\x43ommunicator\x12H\n\nGetBalance\x12\x1d.communication.BalanceRequest\x1a\x1b.communication.BalanceReply\x12H\n\x0eGetLatestBlock\x12\x1b.communication.BlockRequest\x1a\x19.communication.BlockReply\x12W\n\rVerifyAddress\x12#.communication.VerifyAddressRequest\x1a!.communication.VerifyAddressReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "communication_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_BALANCEREQUEST"]._serialized_start = 38
    _globals["_BALANCEREQUEST"]._serialized_end = 71
    _globals["_BALANCEREPLY"]._serialized_start = 73
    _globals["_BALANCEREPLY"]._serialized_end = 104
    _globals["_BLOCKREQUEST"]._serialized_start = 106
    _globals["_BLOCKREQUEST"]._serialized_end = 120
    _globals["_BLOCKREPLY"]._serialized_start = 122
    _globals["_BLOCKREPLY"]._serialized_end = 212
    _globals["_VERIFYADDRESSREQUEST"]._serialized_start = 214
    _globals["_VERIFYADDRESSREQUEST"]._serialized_end = 253
    _globals["_VERIFYADDRESSREPLY"]._serialized_start = 255
    _globals["_VERIFYADDRESSREPLY"]._serialized_end = 296
    _globals["_COMMUNICATOR"]._serialized_start = 299
    _globals["_COMMUNICATOR"]._serialized_end = 550
# @@protoc_insertion_point(module_scope)
